server:
  port: 8086

spring:
  application:
    name: carritos-service
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka


  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3308/service_carrito?serverTimezone=UTC
    username: root
    password:


