server:
  port: 8087

spring:
  application:
    name: productos-service
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3308/service_producto?serverTimezone=UTC
    username: root
    password:

